// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RegisterProtocol.proto

package org.wls.tcpthrough.model;

public final class ManagerProtocolBuf {
  private ManagerProtocolBuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface RegisterProtocolOrBuilder extends
      // @@protoc_insertion_point(interface_extends:RegisterProtocol)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    String getName();
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string password = 2;</code>
     * @return The password.
     */
    String getPassword();
    /**
     * <code>string password = 2;</code>
     * @return The bytes for password.
     */
    com.google.protobuf.ByteString
        getPasswordBytes();

    /**
     * <code>int32 remoteProxyPort = 3;</code>
     * @return The remoteProxyPort.
     */
    int getRemoteProxyPort();

    /**
     * <code>bool isAuth = 4;</code>
     * @return The isAuth.
     */
    boolean getIsAuth();

    /**
     * <code>bool isEncrypt = 5;</code>
     * @return The isEncrypt.
     */
    boolean getIsEncrypt();

    /**
     * <code>string privateKey = 6;</code>
     * @return The privateKey.
     */
    String getPrivateKey();
    /**
     * <code>string privateKey = 6;</code>
     * @return The bytes for privateKey.
     */
    com.google.protobuf.ByteString
        getPrivateKeyBytes();

    /**
     * <code>string secretKey = 7;</code>
     * @return The secretKey.
     */
    String getSecretKey();
    /**
     * <code>string secretKey = 7;</code>
     * @return The bytes for secretKey.
     */
    com.google.protobuf.ByteString
        getSecretKeyBytes();

    /**
     * <code>string nameMd5 = 8;</code>
     * @return The nameMd5.
     */
    String getNameMd5();
    /**
     * <code>string nameMd5 = 8;</code>
     * @return The bytes for nameMd5.
     */
    com.google.protobuf.ByteString
        getNameMd5Bytes();

    /**
     * <code>string secretKeyMd5 = 9;</code>
     * @return The secretKeyMd5.
     */
    String getSecretKeyMd5();
    /**
     * <code>string secretKeyMd5 = 9;</code>
     * @return The bytes for secretKeyMd5.
     */
    com.google.protobuf.ByteString
        getSecretKeyMd5Bytes();

    /**
     * <code>string localHost = 10;</code>
     * @return The localHost.
     */
    String getLocalHost();
    /**
     * <code>string localHost = 10;</code>
     * @return The bytes for localHost.
     */
    com.google.protobuf.ByteString
        getLocalHostBytes();

    /**
     * <code>int32 localPort = 11;</code>
     * @return The localPort.
     */
    int getLocalPort();

    /**
     * <code>string remoteHost = 12;</code>
     * @return The remoteHost.
     */
    String getRemoteHost();
    /**
     * <code>string remoteHost = 12;</code>
     * @return The bytes for remoteHost.
     */
    com.google.protobuf.ByteString
        getRemoteHostBytes();

    /**
     * <code>int32 remoteDataPort = 13;</code>
     * @return The remoteDataPort.
     */
    int getRemoteDataPort();

    /**
     * <code>int32 remoteManagerPort = 14;</code>
     * @return The remoteManagerPort.
     */
    int getRemoteManagerPort();
  }
  /**
   * Protobuf type {@code RegisterProtocol}
   */
  public  static final class RegisterProtocol extends
      com.google.protobuf.GeneratedMessageLite<
          RegisterProtocol, RegisterProtocol.Builder> implements
      // @@protoc_insertion_point(message_implements:RegisterProtocol)
      RegisterProtocolOrBuilder {
    private RegisterProtocol() {
      name_ = "";
      password_ = "";
      privateKey_ = "";
      secretKey_ = "";
      nameMd5_ = "";
      secretKeyMd5_ = "";
      localHost_ = "";
      remoteHost_ = "";
    }
    public static final int NAME_FIELD_NUMBER = 1;
    private String name_;
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    @Override
    public String getName() {
      return name_;
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    @Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(name_);
    }
    /**
     * <code>string name = 1;</code>
     * @param value The name to set.
     */
    private void setName(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      name_ = value;
    }
    /**
     * <code>string name = 1;</code>
     */
    private void clearName() {

      name_ = getDefaultInstance().getName();
    }
    /**
     * <code>string name = 1;</code>
     * @param value The bytes for name to set.
     */
    private void setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      name_ = value.toStringUtf8();
    }

    public static final int PASSWORD_FIELD_NUMBER = 2;
    private String password_;
    /**
     * <code>string password = 2;</code>
     * @return The password.
     */
    @Override
    public String getPassword() {
      return password_;
    }
    /**
     * <code>string password = 2;</code>
     * @return The bytes for password.
     */
    @Override
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(password_);
    }
    /**
     * <code>string password = 2;</code>
     * @param value The password to set.
     */
    private void setPassword(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      password_ = value;
    }
    /**
     * <code>string password = 2;</code>
     */
    private void clearPassword() {

      password_ = getDefaultInstance().getPassword();
    }
    /**
     * <code>string password = 2;</code>
     * @param value The bytes for password to set.
     */
    private void setPasswordBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      password_ = value.toStringUtf8();
    }

    public static final int REMOTEPROXYPORT_FIELD_NUMBER = 3;
    private int remoteProxyPort_;
    /**
     * <code>int32 remoteProxyPort = 3;</code>
     * @return The remoteProxyPort.
     */
    @Override
    public int getRemoteProxyPort() {
      return remoteProxyPort_;
    }
    /**
     * <code>int32 remoteProxyPort = 3;</code>
     * @param value The remoteProxyPort to set.
     */
    private void setRemoteProxyPort(int value) {

      remoteProxyPort_ = value;
    }
    /**
     * <code>int32 remoteProxyPort = 3;</code>
     */
    private void clearRemoteProxyPort() {

      remoteProxyPort_ = 0;
    }

    public static final int ISAUTH_FIELD_NUMBER = 4;
    private boolean isAuth_;
    /**
     * <code>bool isAuth = 4;</code>
     * @return The isAuth.
     */
    @Override
    public boolean getIsAuth() {
      return isAuth_;
    }
    /**
     * <code>bool isAuth = 4;</code>
     * @param value The isAuth to set.
     */
    private void setIsAuth(boolean value) {

      isAuth_ = value;
    }
    /**
     * <code>bool isAuth = 4;</code>
     */
    private void clearIsAuth() {

      isAuth_ = false;
    }

    public static final int ISENCRYPT_FIELD_NUMBER = 5;
    private boolean isEncrypt_;
    /**
     * <code>bool isEncrypt = 5;</code>
     * @return The isEncrypt.
     */
    @Override
    public boolean getIsEncrypt() {
      return isEncrypt_;
    }
    /**
     * <code>bool isEncrypt = 5;</code>
     * @param value The isEncrypt to set.
     */
    private void setIsEncrypt(boolean value) {

      isEncrypt_ = value;
    }
    /**
     * <code>bool isEncrypt = 5;</code>
     */
    private void clearIsEncrypt() {

      isEncrypt_ = false;
    }

    public static final int PRIVATEKEY_FIELD_NUMBER = 6;
    private String privateKey_;
    /**
     * <code>string privateKey = 6;</code>
     * @return The privateKey.
     */
    @Override
    public String getPrivateKey() {
      return privateKey_;
    }
    /**
     * <code>string privateKey = 6;</code>
     * @return The bytes for privateKey.
     */
    @Override
    public com.google.protobuf.ByteString
        getPrivateKeyBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(privateKey_);
    }
    /**
     * <code>string privateKey = 6;</code>
     * @param value The privateKey to set.
     */
    private void setPrivateKey(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      privateKey_ = value;
    }
    /**
     * <code>string privateKey = 6;</code>
     */
    private void clearPrivateKey() {

      privateKey_ = getDefaultInstance().getPrivateKey();
    }
    /**
     * <code>string privateKey = 6;</code>
     * @param value The bytes for privateKey to set.
     */
    private void setPrivateKeyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      privateKey_ = value.toStringUtf8();
    }

    public static final int SECRETKEY_FIELD_NUMBER = 7;
    private String secretKey_;
    /**
     * <code>string secretKey = 7;</code>
     * @return The secretKey.
     */
    @Override
    public String getSecretKey() {
      return secretKey_;
    }
    /**
     * <code>string secretKey = 7;</code>
     * @return The bytes for secretKey.
     */
    @Override
    public com.google.protobuf.ByteString
        getSecretKeyBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(secretKey_);
    }
    /**
     * <code>string secretKey = 7;</code>
     * @param value The secretKey to set.
     */
    private void setSecretKey(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      secretKey_ = value;
    }
    /**
     * <code>string secretKey = 7;</code>
     */
    private void clearSecretKey() {

      secretKey_ = getDefaultInstance().getSecretKey();
    }
    /**
     * <code>string secretKey = 7;</code>
     * @param value The bytes for secretKey to set.
     */
    private void setSecretKeyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      secretKey_ = value.toStringUtf8();
    }

    public static final int NAMEMD5_FIELD_NUMBER = 8;
    private String nameMd5_;
    /**
     * <code>string nameMd5 = 8;</code>
     * @return The nameMd5.
     */
    @Override
    public String getNameMd5() {
      return nameMd5_;
    }
    /**
     * <code>string nameMd5 = 8;</code>
     * @return The bytes for nameMd5.
     */
    @Override
    public com.google.protobuf.ByteString
        getNameMd5Bytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(nameMd5_);
    }
    /**
     * <code>string nameMd5 = 8;</code>
     * @param value The nameMd5 to set.
     */
    private void setNameMd5(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      nameMd5_ = value;
    }
    /**
     * <code>string nameMd5 = 8;</code>
     */
    private void clearNameMd5() {

      nameMd5_ = getDefaultInstance().getNameMd5();
    }
    /**
     * <code>string nameMd5 = 8;</code>
     * @param value The bytes for nameMd5 to set.
     */
    private void setNameMd5Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      nameMd5_ = value.toStringUtf8();
    }

    public static final int SECRETKEYMD5_FIELD_NUMBER = 9;
    private String secretKeyMd5_;
    /**
     * <code>string secretKeyMd5 = 9;</code>
     * @return The secretKeyMd5.
     */
    @Override
    public String getSecretKeyMd5() {
      return secretKeyMd5_;
    }
    /**
     * <code>string secretKeyMd5 = 9;</code>
     * @return The bytes for secretKeyMd5.
     */
    @Override
    public com.google.protobuf.ByteString
        getSecretKeyMd5Bytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(secretKeyMd5_);
    }
    /**
     * <code>string secretKeyMd5 = 9;</code>
     * @param value The secretKeyMd5 to set.
     */
    private void setSecretKeyMd5(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      secretKeyMd5_ = value;
    }
    /**
     * <code>string secretKeyMd5 = 9;</code>
     */
    private void clearSecretKeyMd5() {

      secretKeyMd5_ = getDefaultInstance().getSecretKeyMd5();
    }
    /**
     * <code>string secretKeyMd5 = 9;</code>
     * @param value The bytes for secretKeyMd5 to set.
     */
    private void setSecretKeyMd5Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      secretKeyMd5_ = value.toStringUtf8();
    }

    public static final int LOCALHOST_FIELD_NUMBER = 10;
    private String localHost_;
    /**
     * <code>string localHost = 10;</code>
     * @return The localHost.
     */
    @Override
    public String getLocalHost() {
      return localHost_;
    }
    /**
     * <code>string localHost = 10;</code>
     * @return The bytes for localHost.
     */
    @Override
    public com.google.protobuf.ByteString
        getLocalHostBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(localHost_);
    }
    /**
     * <code>string localHost = 10;</code>
     * @param value The localHost to set.
     */
    private void setLocalHost(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      localHost_ = value;
    }
    /**
     * <code>string localHost = 10;</code>
     */
    private void clearLocalHost() {

      localHost_ = getDefaultInstance().getLocalHost();
    }
    /**
     * <code>string localHost = 10;</code>
     * @param value The bytes for localHost to set.
     */
    private void setLocalHostBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      localHost_ = value.toStringUtf8();
    }

    public static final int LOCALPORT_FIELD_NUMBER = 11;
    private int localPort_;
    /**
     * <code>int32 localPort = 11;</code>
     * @return The localPort.
     */
    @Override
    public int getLocalPort() {
      return localPort_;
    }
    /**
     * <code>int32 localPort = 11;</code>
     * @param value The localPort to set.
     */
    private void setLocalPort(int value) {

      localPort_ = value;
    }
    /**
     * <code>int32 localPort = 11;</code>
     */
    private void clearLocalPort() {

      localPort_ = 0;
    }

    public static final int REMOTEHOST_FIELD_NUMBER = 12;
    private String remoteHost_;
    /**
     * <code>string remoteHost = 12;</code>
     * @return The remoteHost.
     */
    @Override
    public String getRemoteHost() {
      return remoteHost_;
    }
    /**
     * <code>string remoteHost = 12;</code>
     * @return The bytes for remoteHost.
     */
    @Override
    public com.google.protobuf.ByteString
        getRemoteHostBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(remoteHost_);
    }
    /**
     * <code>string remoteHost = 12;</code>
     * @param value The remoteHost to set.
     */
    private void setRemoteHost(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      remoteHost_ = value;
    }
    /**
     * <code>string remoteHost = 12;</code>
     */
    private void clearRemoteHost() {

      remoteHost_ = getDefaultInstance().getRemoteHost();
    }
    /**
     * <code>string remoteHost = 12;</code>
     * @param value The bytes for remoteHost to set.
     */
    private void setRemoteHostBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      remoteHost_ = value.toStringUtf8();
    }

    public static final int REMOTEDATAPORT_FIELD_NUMBER = 13;
    private int remoteDataPort_;
    /**
     * <code>int32 remoteDataPort = 13;</code>
     * @return The remoteDataPort.
     */
    @Override
    public int getRemoteDataPort() {
      return remoteDataPort_;
    }
    /**
     * <code>int32 remoteDataPort = 13;</code>
     * @param value The remoteDataPort to set.
     */
    private void setRemoteDataPort(int value) {

      remoteDataPort_ = value;
    }
    /**
     * <code>int32 remoteDataPort = 13;</code>
     */
    private void clearRemoteDataPort() {

      remoteDataPort_ = 0;
    }

    public static final int REMOTEMANAGERPORT_FIELD_NUMBER = 14;
    private int remoteManagerPort_;
    /**
     * <code>int32 remoteManagerPort = 14;</code>
     * @return The remoteManagerPort.
     */
    @Override
    public int getRemoteManagerPort() {
      return remoteManagerPort_;
    }
    /**
     * <code>int32 remoteManagerPort = 14;</code>
     * @param value The remoteManagerPort to set.
     */
    private void setRemoteManagerPort(int value) {

      remoteManagerPort_ = value;
    }
    /**
     * <code>int32 remoteManagerPort = 14;</code>
     */
    private void clearRemoteManagerPort() {

      remoteManagerPort_ = 0;
    }

    public static RegisterProtocol parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static RegisterProtocol parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static RegisterProtocol parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static RegisterProtocol parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static RegisterProtocol parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static RegisterProtocol parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static RegisterProtocol parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static RegisterProtocol parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static RegisterProtocol parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static RegisterProtocol parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static RegisterProtocol parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static RegisterProtocol parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(RegisterProtocol prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code RegisterProtocol}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          RegisterProtocol, Builder> implements
        // @@protoc_insertion_point(builder_implements:RegisterProtocol)
        RegisterProtocolOrBuilder {
      // Construct using org.wls.tcpthrough.model.ManagerProtocolBuf.RegisterProtocol.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>string name = 1;</code>
       * @return The name.
       */
      @Override
      public String getName() {
        return instance.getName();
      }
      /**
       * <code>string name = 1;</code>
       * @return The bytes for name.
       */
      @Override
      public com.google.protobuf.ByteString
          getNameBytes() {
        return instance.getNameBytes();
      }
      /**
       * <code>string name = 1;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          String value) {
        copyOnWrite();
        instance.setName(value);
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        copyOnWrite();
        instance.clearName();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setNameBytes(value);
        return this;
      }

      /**
       * <code>string password = 2;</code>
       * @return The password.
       */
      @Override
      public String getPassword() {
        return instance.getPassword();
      }
      /**
       * <code>string password = 2;</code>
       * @return The bytes for password.
       */
      @Override
      public com.google.protobuf.ByteString
          getPasswordBytes() {
        return instance.getPasswordBytes();
      }
      /**
       * <code>string password = 2;</code>
       * @param value The password to set.
       * @return This builder for chaining.
       */
      public Builder setPassword(
          String value) {
        copyOnWrite();
        instance.setPassword(value);
        return this;
      }
      /**
       * <code>string password = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPassword() {
        copyOnWrite();
        instance.clearPassword();
        return this;
      }
      /**
       * <code>string password = 2;</code>
       * @param value The bytes for password to set.
       * @return This builder for chaining.
       */
      public Builder setPasswordBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setPasswordBytes(value);
        return this;
      }

      /**
       * <code>int32 remoteProxyPort = 3;</code>
       * @return The remoteProxyPort.
       */
      @Override
      public int getRemoteProxyPort() {
        return instance.getRemoteProxyPort();
      }
      /**
       * <code>int32 remoteProxyPort = 3;</code>
       * @param value The remoteProxyPort to set.
       * @return This builder for chaining.
       */
      public Builder setRemoteProxyPort(int value) {
        copyOnWrite();
        instance.setRemoteProxyPort(value);
        return this;
      }
      /**
       * <code>int32 remoteProxyPort = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearRemoteProxyPort() {
        copyOnWrite();
        instance.clearRemoteProxyPort();
        return this;
      }

      /**
       * <code>bool isAuth = 4;</code>
       * @return The isAuth.
       */
      @Override
      public boolean getIsAuth() {
        return instance.getIsAuth();
      }
      /**
       * <code>bool isAuth = 4;</code>
       * @param value The isAuth to set.
       * @return This builder for chaining.
       */
      public Builder setIsAuth(boolean value) {
        copyOnWrite();
        instance.setIsAuth(value);
        return this;
      }
      /**
       * <code>bool isAuth = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsAuth() {
        copyOnWrite();
        instance.clearIsAuth();
        return this;
      }

      /**
       * <code>bool isEncrypt = 5;</code>
       * @return The isEncrypt.
       */
      @Override
      public boolean getIsEncrypt() {
        return instance.getIsEncrypt();
      }
      /**
       * <code>bool isEncrypt = 5;</code>
       * @param value The isEncrypt to set.
       * @return This builder for chaining.
       */
      public Builder setIsEncrypt(boolean value) {
        copyOnWrite();
        instance.setIsEncrypt(value);
        return this;
      }
      /**
       * <code>bool isEncrypt = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsEncrypt() {
        copyOnWrite();
        instance.clearIsEncrypt();
        return this;
      }

      /**
       * <code>string privateKey = 6;</code>
       * @return The privateKey.
       */
      @Override
      public String getPrivateKey() {
        return instance.getPrivateKey();
      }
      /**
       * <code>string privateKey = 6;</code>
       * @return The bytes for privateKey.
       */
      @Override
      public com.google.protobuf.ByteString
          getPrivateKeyBytes() {
        return instance.getPrivateKeyBytes();
      }
      /**
       * <code>string privateKey = 6;</code>
       * @param value The privateKey to set.
       * @return This builder for chaining.
       */
      public Builder setPrivateKey(
          String value) {
        copyOnWrite();
        instance.setPrivateKey(value);
        return this;
      }
      /**
       * <code>string privateKey = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearPrivateKey() {
        copyOnWrite();
        instance.clearPrivateKey();
        return this;
      }
      /**
       * <code>string privateKey = 6;</code>
       * @param value The bytes for privateKey to set.
       * @return This builder for chaining.
       */
      public Builder setPrivateKeyBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setPrivateKeyBytes(value);
        return this;
      }

      /**
       * <code>string secretKey = 7;</code>
       * @return The secretKey.
       */
      @Override
      public String getSecretKey() {
        return instance.getSecretKey();
      }
      /**
       * <code>string secretKey = 7;</code>
       * @return The bytes for secretKey.
       */
      @Override
      public com.google.protobuf.ByteString
          getSecretKeyBytes() {
        return instance.getSecretKeyBytes();
      }
      /**
       * <code>string secretKey = 7;</code>
       * @param value The secretKey to set.
       * @return This builder for chaining.
       */
      public Builder setSecretKey(
          String value) {
        copyOnWrite();
        instance.setSecretKey(value);
        return this;
      }
      /**
       * <code>string secretKey = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearSecretKey() {
        copyOnWrite();
        instance.clearSecretKey();
        return this;
      }
      /**
       * <code>string secretKey = 7;</code>
       * @param value The bytes for secretKey to set.
       * @return This builder for chaining.
       */
      public Builder setSecretKeyBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setSecretKeyBytes(value);
        return this;
      }

      /**
       * <code>string nameMd5 = 8;</code>
       * @return The nameMd5.
       */
      @Override
      public String getNameMd5() {
        return instance.getNameMd5();
      }
      /**
       * <code>string nameMd5 = 8;</code>
       * @return The bytes for nameMd5.
       */
      @Override
      public com.google.protobuf.ByteString
          getNameMd5Bytes() {
        return instance.getNameMd5Bytes();
      }
      /**
       * <code>string nameMd5 = 8;</code>
       * @param value The nameMd5 to set.
       * @return This builder for chaining.
       */
      public Builder setNameMd5(
          String value) {
        copyOnWrite();
        instance.setNameMd5(value);
        return this;
      }
      /**
       * <code>string nameMd5 = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearNameMd5() {
        copyOnWrite();
        instance.clearNameMd5();
        return this;
      }
      /**
       * <code>string nameMd5 = 8;</code>
       * @param value The bytes for nameMd5 to set.
       * @return This builder for chaining.
       */
      public Builder setNameMd5Bytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setNameMd5Bytes(value);
        return this;
      }

      /**
       * <code>string secretKeyMd5 = 9;</code>
       * @return The secretKeyMd5.
       */
      @Override
      public String getSecretKeyMd5() {
        return instance.getSecretKeyMd5();
      }
      /**
       * <code>string secretKeyMd5 = 9;</code>
       * @return The bytes for secretKeyMd5.
       */
      @Override
      public com.google.protobuf.ByteString
          getSecretKeyMd5Bytes() {
        return instance.getSecretKeyMd5Bytes();
      }
      /**
       * <code>string secretKeyMd5 = 9;</code>
       * @param value The secretKeyMd5 to set.
       * @return This builder for chaining.
       */
      public Builder setSecretKeyMd5(
          String value) {
        copyOnWrite();
        instance.setSecretKeyMd5(value);
        return this;
      }
      /**
       * <code>string secretKeyMd5 = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearSecretKeyMd5() {
        copyOnWrite();
        instance.clearSecretKeyMd5();
        return this;
      }
      /**
       * <code>string secretKeyMd5 = 9;</code>
       * @param value The bytes for secretKeyMd5 to set.
       * @return This builder for chaining.
       */
      public Builder setSecretKeyMd5Bytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setSecretKeyMd5Bytes(value);
        return this;
      }

      /**
       * <code>string localHost = 10;</code>
       * @return The localHost.
       */
      @Override
      public String getLocalHost() {
        return instance.getLocalHost();
      }
      /**
       * <code>string localHost = 10;</code>
       * @return The bytes for localHost.
       */
      @Override
      public com.google.protobuf.ByteString
          getLocalHostBytes() {
        return instance.getLocalHostBytes();
      }
      /**
       * <code>string localHost = 10;</code>
       * @param value The localHost to set.
       * @return This builder for chaining.
       */
      public Builder setLocalHost(
          String value) {
        copyOnWrite();
        instance.setLocalHost(value);
        return this;
      }
      /**
       * <code>string localHost = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearLocalHost() {
        copyOnWrite();
        instance.clearLocalHost();
        return this;
      }
      /**
       * <code>string localHost = 10;</code>
       * @param value The bytes for localHost to set.
       * @return This builder for chaining.
       */
      public Builder setLocalHostBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setLocalHostBytes(value);
        return this;
      }

      /**
       * <code>int32 localPort = 11;</code>
       * @return The localPort.
       */
      @Override
      public int getLocalPort() {
        return instance.getLocalPort();
      }
      /**
       * <code>int32 localPort = 11;</code>
       * @param value The localPort to set.
       * @return This builder for chaining.
       */
      public Builder setLocalPort(int value) {
        copyOnWrite();
        instance.setLocalPort(value);
        return this;
      }
      /**
       * <code>int32 localPort = 11;</code>
       * @return This builder for chaining.
       */
      public Builder clearLocalPort() {
        copyOnWrite();
        instance.clearLocalPort();
        return this;
      }

      /**
       * <code>string remoteHost = 12;</code>
       * @return The remoteHost.
       */
      @Override
      public String getRemoteHost() {
        return instance.getRemoteHost();
      }
      /**
       * <code>string remoteHost = 12;</code>
       * @return The bytes for remoteHost.
       */
      @Override
      public com.google.protobuf.ByteString
          getRemoteHostBytes() {
        return instance.getRemoteHostBytes();
      }
      /**
       * <code>string remoteHost = 12;</code>
       * @param value The remoteHost to set.
       * @return This builder for chaining.
       */
      public Builder setRemoteHost(
          String value) {
        copyOnWrite();
        instance.setRemoteHost(value);
        return this;
      }
      /**
       * <code>string remoteHost = 12;</code>
       * @return This builder for chaining.
       */
      public Builder clearRemoteHost() {
        copyOnWrite();
        instance.clearRemoteHost();
        return this;
      }
      /**
       * <code>string remoteHost = 12;</code>
       * @param value The bytes for remoteHost to set.
       * @return This builder for chaining.
       */
      public Builder setRemoteHostBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setRemoteHostBytes(value);
        return this;
      }

      /**
       * <code>int32 remoteDataPort = 13;</code>
       * @return The remoteDataPort.
       */
      @Override
      public int getRemoteDataPort() {
        return instance.getRemoteDataPort();
      }
      /**
       * <code>int32 remoteDataPort = 13;</code>
       * @param value The remoteDataPort to set.
       * @return This builder for chaining.
       */
      public Builder setRemoteDataPort(int value) {
        copyOnWrite();
        instance.setRemoteDataPort(value);
        return this;
      }
      /**
       * <code>int32 remoteDataPort = 13;</code>
       * @return This builder for chaining.
       */
      public Builder clearRemoteDataPort() {
        copyOnWrite();
        instance.clearRemoteDataPort();
        return this;
      }

      /**
       * <code>int32 remoteManagerPort = 14;</code>
       * @return The remoteManagerPort.
       */
      @Override
      public int getRemoteManagerPort() {
        return instance.getRemoteManagerPort();
      }
      /**
       * <code>int32 remoteManagerPort = 14;</code>
       * @param value The remoteManagerPort to set.
       * @return This builder for chaining.
       */
      public Builder setRemoteManagerPort(int value) {
        copyOnWrite();
        instance.setRemoteManagerPort(value);
        return this;
      }
      /**
       * <code>int32 remoteManagerPort = 14;</code>
       * @return This builder for chaining.
       */
      public Builder clearRemoteManagerPort() {
        copyOnWrite();
        instance.clearRemoteManagerPort();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:RegisterProtocol)
    }
    @Override
    @SuppressWarnings({"unchecked", "fallthrough"})
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new RegisterProtocol();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            Object[] objects = new Object[] {
              "name_",
              "password_",
              "remoteProxyPort_",
              "isAuth_",
              "isEncrypt_",
              "privateKey_",
              "secretKey_",
              "nameMd5_",
              "secretKeyMd5_",
              "localHost_",
              "localPort_",
              "remoteHost_",
              "remoteDataPort_",
              "remoteManagerPort_",
            };
            String info =
                "\u0000\u000e\u0000\u0000\u0001\u000e\u000e\u0000\u0000\u0000\u0001\u0208\u0002\u0208" +
                "\u0003\u0004\u0004\u0007\u0005\u0007\u0006\u0208\u0007\u0208\b\u0208\t\u0208\n\u0208" +
                "\u000b\u0004\f\u0208\r\u0004\u000e\u0004";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<RegisterProtocol> parser = PARSER;
          if (parser == null) {
            synchronized (RegisterProtocol.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<RegisterProtocol>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:RegisterProtocol)
    private static final RegisterProtocol DEFAULT_INSTANCE;
    static {
      RegisterProtocol defaultInstance = new RegisterProtocol();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        RegisterProtocol.class, defaultInstance);
    }

    public static RegisterProtocol getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<RegisterProtocol> PARSER;

    public static com.google.protobuf.Parser<RegisterProtocol> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface ManagerResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ManagerResponse)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     * 1-&gt;res, 2-&gt;new connection
     * </pre>
     *
     * <code>int32 type = 1;</code>
     * @return The type.
     */
    int getType();

    /**
     * <pre>
     * type=1 -&gt; 如果加密的话，是密码; type=2 -&gt; channel uuid,建立连接的时候用来告诉server
     * </pre>
     *
     * <code>string channel = 2;</code>
     * @return The channel.
     */
    String getChannel();
    /**
     * <pre>
     * type=1 -&gt; 如果加密的话，是密码; type=2 -&gt; channel uuid,建立连接的时候用来告诉server
     * </pre>
     *
     * <code>string channel = 2;</code>
     * @return The bytes for channel.
     */
    com.google.protobuf.ByteString
        getChannelBytes();

    /**
     * <code>string channelMd5 = 3;</code>
     * @return The channelMd5.
     */
    String getChannelMd5();
    /**
     * <code>string channelMd5 = 3;</code>
     * @return The bytes for channelMd5.
     */
    com.google.protobuf.ByteString
        getChannelMd5Bytes();
  }
  /**
   * Protobuf type {@code ManagerResponse}
   */
  public  static final class ManagerResponse extends
      com.google.protobuf.GeneratedMessageLite<
          ManagerResponse, ManagerResponse.Builder> implements
      // @@protoc_insertion_point(message_implements:ManagerResponse)
      ManagerResponseOrBuilder {
    private ManagerResponse() {
      channel_ = "";
      channelMd5_ = "";
    }
    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <pre>
     * 1-&gt;res, 2-&gt;new connection
     * </pre>
     *
     * <code>int32 type = 1;</code>
     * @return The type.
     */
    @Override
    public int getType() {
      return type_;
    }
    /**
     * <pre>
     * 1-&gt;res, 2-&gt;new connection
     * </pre>
     *
     * <code>int32 type = 1;</code>
     * @param value The type to set.
     */
    private void setType(int value) {

      type_ = value;
    }
    /**
     * <pre>
     * 1-&gt;res, 2-&gt;new connection
     * </pre>
     *
     * <code>int32 type = 1;</code>
     */
    private void clearType() {

      type_ = 0;
    }

    public static final int CHANNEL_FIELD_NUMBER = 2;
    private String channel_;
    /**
     * <pre>
     * type=1 -&gt; 如果加密的话，是密码; type=2 -&gt; channel uuid,建立连接的时候用来告诉server
     * </pre>
     *
     * <code>string channel = 2;</code>
     * @return The channel.
     */
    @Override
    public String getChannel() {
      return channel_;
    }
    /**
     * <pre>
     * type=1 -&gt; 如果加密的话，是密码; type=2 -&gt; channel uuid,建立连接的时候用来告诉server
     * </pre>
     *
     * <code>string channel = 2;</code>
     * @return The bytes for channel.
     */
    @Override
    public com.google.protobuf.ByteString
        getChannelBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(channel_);
    }
    /**
     * <pre>
     * type=1 -&gt; 如果加密的话，是密码; type=2 -&gt; channel uuid,建立连接的时候用来告诉server
     * </pre>
     *
     * <code>string channel = 2;</code>
     * @param value The channel to set.
     */
    private void setChannel(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      channel_ = value;
    }
    /**
     * <pre>
     * type=1 -&gt; 如果加密的话，是密码; type=2 -&gt; channel uuid,建立连接的时候用来告诉server
     * </pre>
     *
     * <code>string channel = 2;</code>
     */
    private void clearChannel() {

      channel_ = getDefaultInstance().getChannel();
    }
    /**
     * <pre>
     * type=1 -&gt; 如果加密的话，是密码; type=2 -&gt; channel uuid,建立连接的时候用来告诉server
     * </pre>
     *
     * <code>string channel = 2;</code>
     * @param value The bytes for channel to set.
     */
    private void setChannelBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      channel_ = value.toStringUtf8();
    }

    public static final int CHANNELMD5_FIELD_NUMBER = 3;
    private String channelMd5_;
    /**
     * <code>string channelMd5 = 3;</code>
     * @return The channelMd5.
     */
    @Override
    public String getChannelMd5() {
      return channelMd5_;
    }
    /**
     * <code>string channelMd5 = 3;</code>
     * @return The bytes for channelMd5.
     */
    @Override
    public com.google.protobuf.ByteString
        getChannelMd5Bytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(channelMd5_);
    }
    /**
     * <code>string channelMd5 = 3;</code>
     * @param value The channelMd5 to set.
     */
    private void setChannelMd5(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      channelMd5_ = value;
    }
    /**
     * <code>string channelMd5 = 3;</code>
     */
    private void clearChannelMd5() {

      channelMd5_ = getDefaultInstance().getChannelMd5();
    }
    /**
     * <code>string channelMd5 = 3;</code>
     * @param value The bytes for channelMd5 to set.
     */
    private void setChannelMd5Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      channelMd5_ = value.toStringUtf8();
    }

    public static ManagerResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ManagerResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ManagerResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ManagerResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ManagerResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ManagerResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ManagerResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static ManagerResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static ManagerResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static ManagerResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static ManagerResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static ManagerResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(ManagerResponse prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code ManagerResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          ManagerResponse, Builder> implements
        // @@protoc_insertion_point(builder_implements:ManagerResponse)
        ManagerResponseOrBuilder {
      // Construct using org.wls.tcpthrough.model.ManagerProtocolBuf.ManagerResponse.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       * 1-&gt;res, 2-&gt;new connection
       * </pre>
       *
       * <code>int32 type = 1;</code>
       * @return The type.
       */
      @Override
      public int getType() {
        return instance.getType();
      }
      /**
       * <pre>
       * 1-&gt;res, 2-&gt;new connection
       * </pre>
       *
       * <code>int32 type = 1;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(int value) {
        copyOnWrite();
        instance.setType(value);
        return this;
      }
      /**
       * <pre>
       * 1-&gt;res, 2-&gt;new connection
       * </pre>
       *
       * <code>int32 type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        copyOnWrite();
        instance.clearType();
        return this;
      }

      /**
       * <pre>
       * type=1 -&gt; 如果加密的话，是密码; type=2 -&gt; channel uuid,建立连接的时候用来告诉server
       * </pre>
       *
       * <code>string channel = 2;</code>
       * @return The channel.
       */
      @Override
      public String getChannel() {
        return instance.getChannel();
      }
      /**
       * <pre>
       * type=1 -&gt; 如果加密的话，是密码; type=2 -&gt; channel uuid,建立连接的时候用来告诉server
       * </pre>
       *
       * <code>string channel = 2;</code>
       * @return The bytes for channel.
       */
      @Override
      public com.google.protobuf.ByteString
          getChannelBytes() {
        return instance.getChannelBytes();
      }
      /**
       * <pre>
       * type=1 -&gt; 如果加密的话，是密码; type=2 -&gt; channel uuid,建立连接的时候用来告诉server
       * </pre>
       *
       * <code>string channel = 2;</code>
       * @param value The channel to set.
       * @return This builder for chaining.
       */
      public Builder setChannel(
          String value) {
        copyOnWrite();
        instance.setChannel(value);
        return this;
      }
      /**
       * <pre>
       * type=1 -&gt; 如果加密的话，是密码; type=2 -&gt; channel uuid,建立连接的时候用来告诉server
       * </pre>
       *
       * <code>string channel = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearChannel() {
        copyOnWrite();
        instance.clearChannel();
        return this;
      }
      /**
       * <pre>
       * type=1 -&gt; 如果加密的话，是密码; type=2 -&gt; channel uuid,建立连接的时候用来告诉server
       * </pre>
       *
       * <code>string channel = 2;</code>
       * @param value The bytes for channel to set.
       * @return This builder for chaining.
       */
      public Builder setChannelBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setChannelBytes(value);
        return this;
      }

      /**
       * <code>string channelMd5 = 3;</code>
       * @return The channelMd5.
       */
      @Override
      public String getChannelMd5() {
        return instance.getChannelMd5();
      }
      /**
       * <code>string channelMd5 = 3;</code>
       * @return The bytes for channelMd5.
       */
      @Override
      public com.google.protobuf.ByteString
          getChannelMd5Bytes() {
        return instance.getChannelMd5Bytes();
      }
      /**
       * <code>string channelMd5 = 3;</code>
       * @param value The channelMd5 to set.
       * @return This builder for chaining.
       */
      public Builder setChannelMd5(
          String value) {
        copyOnWrite();
        instance.setChannelMd5(value);
        return this;
      }
      /**
       * <code>string channelMd5 = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearChannelMd5() {
        copyOnWrite();
        instance.clearChannelMd5();
        return this;
      }
      /**
       * <code>string channelMd5 = 3;</code>
       * @param value The bytes for channelMd5 to set.
       * @return This builder for chaining.
       */
      public Builder setChannelMd5Bytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setChannelMd5Bytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ManagerResponse)
    }
    @Override
    @SuppressWarnings({"unchecked", "fallthrough"})
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new ManagerResponse();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            Object[] objects = new Object[] {
              "type_",
              "channel_",
              "channelMd5_",
            };
            String info =
                "\u0000\u0003\u0000\u0000\u0001\u0003\u0003\u0000\u0000\u0000\u0001\u0004\u0002\u0208" +
                "\u0003\u0208";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<ManagerResponse> parser = PARSER;
          if (parser == null) {
            synchronized (ManagerResponse.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<ManagerResponse>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:ManagerResponse)
    private static final ManagerResponse DEFAULT_INSTANCE;
    static {
      ManagerResponse defaultInstance = new ManagerResponse();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        ManagerResponse.class, defaultInstance);
    }

    public static ManagerResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<ManagerResponse> PARSER;

    public static com.google.protobuf.Parser<ManagerResponse> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
